source 'https://github.com/CocoaPods/Specs.git'

target 'MRGMarqueeLabel_Example', :exclusive => true do
  pod "MRGMarqueeLabel", :path => "../"
end

target 'MRGMarqueeLabel_Tests', :exclusive => true do
  pod "MRGMarqueeLabel", :path => "../"

  
end
